feat: number field uioptions
Byzanteam/taihaku-schemas pull request #15
Opened 2024-05-29 06:29 UTC by shaddollxz

2024-05-29 06:38 UTC, moonRider approved these changes

2024-05-29 06:57 UTC, moonRider commented
> 感觉不需要 `accuracy` 这个选项了，在 JSONSchema 中就可以决定类型到底是 number 还是 integer，在 uiOptions 这里加上就重复了，我们让 number 和 integer 都共用一个 NumberWidget，在 widget 内部根据 schema.type 来决定 input 的精度就够了
> 
> @moonRider @fahchen

意义不同的，JSONSchema 中的格式决定了数据的格式。UIOptions 中的格式只决定这个值在 UI 组件中的显示格式。你类比下 date 的 format

2024-05-29 11:20 UTC, fahchen requested changes

2024-05-29 11:20 UTC, fahchen commented on types/ui_schema/field_type.ts
> +  Number = 'Number',
```suggestion
  Numeric = 'Numeric',
```

2024-05-30 01:56 UTC, fahchen approved these changes

2024-05-30 01:57 UTC, moonRider approved these changes

2024-05-30 01:58 UTC, merged