feat: define TableSchema
Byzanteam/taihaku-schemas pull request #23
Opened 2024-06-25 08:48 UTC by moonRider

* Field
* TableUISchema
* TableSchema

2024-06-25 09:09 UTC, fahchen requested changes
补充点文档

2024-06-25 09:09 UTC, fahchen commented on types/ui_schema/field.ts
> +}
这东西要不就用 string union 吧？

2024-06-25 09:09 UTC, fahchen commented on types/ui_schema/table/mod.ts
> +  & Partial<FieldUISchema<TData>>
`Partial<FieldUISchema<TData>>` 的 key 可能会和 `Partial<TableOptions<TData>>` 冲突

2024-06-25 09:09 UTC, fahchen commented on types/ui_schema/table/example/simple.ts
> +    columnVisibility: {},
例子全一点
1. columnVisibility 给值
2. field ui 也给几个值

2024-06-25 09:13 UTC, fahchen commented on types/ui_schema/table/mod.ts
> +    /** define size and resize of current field */
这句话怎么翻译啊？（resize 没看懂）

2024-06-25 09:13 UTC, fahchen commented on types/ui_schema/table/mod.ts
> +    minSize?: number
number 的单位是什么，文档说明一下

2024-06-25 09:13 UTC, fahchen commented on types/ui_schema/table/mod.ts
> +  }
不需要备注是 initial
```suggestion
  /** The order of table columns(fields) */
  order: Array<keyof TData>
  /** The pinning settings */
  pinning: {
    /** Field names */
    left?: Array<keyof TData>
    right?: Array<keyof TData>
  }
  /** The visibility settings */
  columnVisibility: {
    /** The field name */
    [K in keyof TData]?: boolean
  }
```

2024-06-25 09:13 UTC, shaddollxz commented on types/ui_schema/field.ts
> +}
这个用 enum 好点吧，有些地方可能需要这个进行操作，比如判断

2024-06-25 09:14 UTC, moonRider commented on types/ui_schema/table/mod.ts
> +  & Partial<FieldUISchema<TData>>
> `Partial<FieldUISchema<TData>>` 的 key 可能会和 `Partial<TableOptions<TData>>` 冲突

不会吧，这部分都是我们定义的，不应该冲突的

2024-06-26 01:00 UTC, fahchen requested changes

2024-06-26 01:16 UTC, moonRider commented on types/ui_schema/table/mod.ts
> +    'ui:max-size'?: number
组件那边应该提供默认值，比如 tanstack-table 提供的是
`{ size: 150, 'min-size': 20, 'max-size': Number.MAX_SAFE_INTEGER }`

2024-06-26 01:42 UTC, fahchen commented on types/ui_schema/table/mod.ts
> +    'ui:max-size'?: number
为啥要设计这么多 size 参数啊？我觉得只需要有两个就够了
1. autoSize：根据内容决定，默认为 true，
2. size： 指定初始宽度，当 autoSize 为 false 时有效

2024-06-26 02:34 UTC, fahchen commented on types/ui_schema/table/example/simple.ts
> +    },
这里加一下前缀

2024-06-26 02:34 UTC, fahchen commented on types/ui_schema/table/mod.ts
> +     * enforced during column resizing
要不要把这里面的前缀改成 column 哦，我看很容易写成 column

2024-06-26 02:36 UTC, moonRider commented on types/ui_schema/table/mod.ts
> +     * enforced during column resizing
我也觉得应该用 column，不然在组件中使用的时候还要做一次转化

2024-06-26 02:56 UTC, fahchen approved these changes

2024-06-26 03:04 UTC, shaddollxz approved these changes

2024-06-26 03:07 UTC, merged